
language: php

php:
    - 5.3
    - 5.4
    - 5.5
    - 5.6
    - 7.0

script:
    - vendor/bin/tester -p php tests
    - php -f temp/code-checker/src/code-checker.php

after_failure:
    # Print *.actual content
    - for i in $(find tests -name \*.actual); do echo "--- $i"; cat $i; echo; echo; done

before_script:
    # Install Nette Tester & Code Checker
    - travis_retry composer update --no-interaction --prefer-dist
    - travis_retry composer create-project nette/code-checker temp/code-checker ~2.5 --no-interaction

sudo: false
